hide_for_staff:
  type: bool
  default: false
  description:
    da: "Aktiver dette hvis du ønsker at skjule drowdown for personale brugere."
    en: "Enable this if you want to hide the dropdown for staff users."
pm_recipients:
  type: string
  default: ""
  description:
    da: "Tilføj modtagere til sletning af konto PM. Du kan tilføje flere modtagere brugernavn eller gruppe, adskil med komma. <br> For eksempel: adminsm moderators <br> Note: Den valgte gruppe skal acceptere personlige meddelelser."
    en: "Add recipients to account deletion PM. You can add multiple recipients username or group separate with comma. <br> For example: admins, moderators <br> Note: The selected group have to accept personal messages."
dropdown_button_icon:
  type: string
  default: "question-circle"
  description:
    da: "Her kan du ændre Slet min konto dropdown knap ikonet"
    en: "Here you can change the delete my account dropdown button icon."
request_dropdown_item_icon:
  type: string
  default: "far-trash-alt"
  description:
    da: "Her kan du ændre Sletning af konto dropdown element ikonet"
    en: "Here you can change the account deletion dropdown item icon."
info_dropdown_item_icon:
  type: string
  default: "info-circle"
  description:
    da: "Her kan du ændre mere info dropdown element ikonet."
    en: "Here you can change the more info dropdown item icon."
svg_icons: 
  default: ""
  type: "list"
  list_type: "compact"
  description:
    da: "Liste af FontAwesome 5 ikoner brugt i denne tema komponent."
    en: "List of FontAwesome 5 icons used in this theme component."
